// Code generated by protoc-gen-go. DO NOT EDIT.
// source: phantom.proto

package jojo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RejectHumanityReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectHumanityReq) Reset()         { *m = RejectHumanityReq{} }
func (m *RejectHumanityReq) String() string { return proto.CompactTextString(m) }
func (*RejectHumanityReq) ProtoMessage()    {}
func (*RejectHumanityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbed077fd493b760, []int{0}
}

func (m *RejectHumanityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectHumanityReq.Unmarshal(m, b)
}
func (m *RejectHumanityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectHumanityReq.Marshal(b, m, deterministic)
}
func (m *RejectHumanityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectHumanityReq.Merge(m, src)
}
func (m *RejectHumanityReq) XXX_Size() int {
	return xxx_messageInfo_RejectHumanityReq.Size(m)
}
func (m *RejectHumanityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectHumanityReq.DiscardUnknown(m)
}

var xxx_messageInfo_RejectHumanityReq proto.InternalMessageInfo

func (m *RejectHumanityReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RejectHumanityResp struct {
	Line                 string   `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RejectHumanityResp) Reset()         { *m = RejectHumanityResp{} }
func (m *RejectHumanityResp) String() string { return proto.CompactTextString(m) }
func (*RejectHumanityResp) ProtoMessage()    {}
func (*RejectHumanityResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbed077fd493b760, []int{1}
}

func (m *RejectHumanityResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RejectHumanityResp.Unmarshal(m, b)
}
func (m *RejectHumanityResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RejectHumanityResp.Marshal(b, m, deterministic)
}
func (m *RejectHumanityResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RejectHumanityResp.Merge(m, src)
}
func (m *RejectHumanityResp) XXX_Size() int {
	return xxx_messageInfo_RejectHumanityResp.Size(m)
}
func (m *RejectHumanityResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RejectHumanityResp.DiscardUnknown(m)
}

var xxx_messageInfo_RejectHumanityResp proto.InternalMessageInfo

func (m *RejectHumanityResp) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func init() {
	proto.RegisterType((*RejectHumanityReq)(nil), "jojo.RejectHumanityReq")
	proto.RegisterType((*RejectHumanityResp)(nil), "jojo.RejectHumanityResp")
}

func init() { proto.RegisterFile("phantom.proto", fileDescriptor_cbed077fd493b760) }

var fileDescriptor_cbed077fd493b760 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xc8, 0x48, 0xcc,
	0x2b, 0xc9, 0xcf, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0xca, 0xcf, 0xca, 0x57,
	0x52, 0xe7, 0x12, 0x0c, 0x4a, 0xcd, 0x4a, 0x4d, 0x2e, 0xf1, 0x28, 0xcd, 0x4d, 0xcc, 0xcb, 0x2c,
	0xa9, 0x0c, 0x4a, 0x2d, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x34, 0xb8, 0x84, 0xd0, 0x15, 0x16, 0x17, 0x80, 0x54, 0xe6,
	0x64, 0xe6, 0xc1, 0x55, 0x82, 0xd8, 0x46, 0x7e, 0x5c, 0xec, 0x01, 0x10, 0x9b, 0x84, 0x9c, 0xb9,
	0xf8, 0x50, 0x35, 0x09, 0x89, 0xeb, 0x81, 0xac, 0xd5, 0xc3, 0xb0, 0x53, 0x4a, 0x02, 0xbb, 0x44,
	0x71, 0x41, 0x12, 0x1b, 0xd8, 0xbd, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x40, 0xfb, 0x5d,
	0xb3, 0xc0, 0x00, 0x00, 0x00,
}
